spring.thymeleaf.cache=false
# Pour acc\uFFFDder \uFFFD la console H2

spring.security.user.name=admin
spring.security.user.password=123

# 1. On demande \uFFFD Hibernate de cr\uFFFDer les tables en premier
spring.jpa.hibernate.ddl-auto=update

# 2. On dit \uFFFD Spring d'attendre que JPA soit pr\uFFFDt avant d'initialiser les donn\uFFFDes


# 3. On s'assure que le mode d'initialisation est correct
spring.sql.init.mode=always

# Optionnel : pour voir ce qu'il se passe dans la console
spring.jpa.show-sql=true

# Nom fixe pour la base de donn\u00E9es
spring.datasource.url=jdbc:h2:mem:location_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Indispensable pour que le script data.sql s'ex\u00E9cute sur LA BONNE base
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

